spring:
  application:
    name: cliente-service

  datasource:
    url: jdbc:postgresql://localhost:5433/cliente_db
    username: banco
    password: banco
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081